/*
 * class Screen3Select gets the Teacher name, Reduces First name and Last Name to 
 * teacherName which is auto inserted into CreateNewClassFile Form, Label 2(teacher name),
 * and is used in Filename. ClassCombobox is created and the selected item is used 
 * in CreateNewClassFile Form to display class name (label 1). 'Continue' Button 
 * opens the CreateNewClassFile Form and Cancel button returns user to Main Menu.
 */
package student.records.db;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import static student.records.db.StudentRecordsDB.*;

/**
 *
 * @author mairead
 */
public class SelectClassTeacher extends JInternalFrame implements MouseListener{
    
    public static String cName, tName;
    
    public SelectClassTeacher() {
        super("Name Teacher, Select Class", false, false, false, false);
        initComponents();
        addMouseListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        infoPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        labelPane = new javax.swing.JPanel();
        firstNameLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        classLbl = new javax.swing.JLabel();
        firstNameTxtFld = new javax.swing.JTextField();
        lastNameTxtFld = new javax.swing.JTextField();
        classComBox = new javax.swing.JComboBox();
        btnPane = new javax.swing.JPanel();
        contBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        infoArea.setEditable(false);
        infoArea.setBackground(new java.awt.Color(238, 238, 238));
        infoArea.setColumns(20);
        infoArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        infoArea.setLineWrap(true);
        infoArea.setRows(5);
        infoArea.setText("The class name and teacher name will be displayed "+
                "at the top of each record and will be used as the filename "+
                "when saving. ");
        infoArea.setWrapStyleWord(true);
        infoArea.setAutoscrolls(false);
        jScrollPane1.setViewportView(infoArea);
        
         // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   

        javax.swing.GroupLayout infoPaneLayout = new javax.swing.GroupLayout(infoPane);
        infoPane.setLayout(infoPaneLayout);
        infoPaneLayout.setHorizontalGroup(
            infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        infoPaneLayout.setVerticalGroup(
            infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPaneLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        firstNameLbl.setText("Teacher: First Name");
        firstNameLbl.setName("firstNameLbl"); // NOI18N

        lastNameLbl.setText("Teacher: Last Name");
        lastNameLbl.setName("lastNameLbl"); // NOI18N

        classLbl.setText("Class");
        classLbl.setName("classLbl"); // NOI18N

        firstNameTxtFld.setName("firstNameTxtFld"); // NOI18N

        lastNameTxtFld.setName("lastNameTxtFld"); // NOI18N

        classComBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Junior Infants", "Senior Infants", "First", "Second", "Third", "Fourth", "Fifth", "Sixth" }));
        classComBox.setName("classComBox"); // NOI18N

        javax.swing.GroupLayout labelPaneLayout = new javax.swing.GroupLayout(labelPane);
        labelPane.setLayout(labelPaneLayout);
        labelPaneLayout.setHorizontalGroup(
            labelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelPaneLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(labelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLbl)
                    .addComponent(lastNameLbl)
                    .addComponent(classLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(labelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lastNameTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(classComBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(firstNameTxtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        labelPaneLayout.setVerticalGroup(
            labelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(labelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLbl)
                    .addComponent(firstNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(labelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLbl)
                    .addComponent(lastNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(labelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLbl)
                    .addComponent(classComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contBtn.setText("Continue");
        contBtn.setName("contBtn"); // NOI18N
        contBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPaneLayout = new javax.swing.GroupLayout(btnPane);
        btnPane.setLayout(btnPaneLayout);
        btnPaneLayout.setHorizontalGroup(
            btnPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addContainerGap())
        );
        btnPaneLayout.setVerticalGroup(
            btnPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPaneLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(btnPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(infoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>      
                              
    
    private void contBtnActionPerformed(java.awt.event.ActionEvent evt) { 
       
        if(checkInputFields())
            openCreateRecord();
        else {
            JOptionPane.showMessageDialog(null,"Enter Teacher 'first name' and "
                                + " 'last name' fields\n and Select Class.");               
             checkMaximized(); 
        }//else
    }                                       

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        dispose();
    }                                         
boolean checkInputFields(){
       
        return((firstNameTxtFld.getText().length()>=1)&&(lastNameTxtFld.getText().length()>=2)) ;
       
    }//checkInputFields()

//save the teacher Name and class name
//create an instance of CreateNewClassFile and send the teacherName and 
//class name as arguments to constructor. Close (dispose) SelectClassTeacher form.
private void openCreateRecord(){
        tName="";
        String firstName, lastName;
        firstName=firstNameTxtFld.getText();
        lastName=lastNameTxtFld.getText();
        firstName=firstName.replace("-"," ");
        String[] tokens=firstName.split(" ");
        String initials="";
        if(tokens.length>0){
            for(int i=0; i<tokens.length; i++){
                 initials=initials+tokens[i].charAt(0);
             }//for
            
            }//if

        StringBuilder fileName=new StringBuilder(initials);
        fileName.append("\u005F");
        fileName.append(lastName);
        tName=fileName.toString();

        cName=(String)(classComBox.getSelectedItem());
        
        createClassFile=new CreateNewClassFile();
        createClassFile.setSize(frameDim);
        createClassFile.setVisible(true);
        theDesktop.add(createClassFile); 
        //close selectForm
        selectForm.dispose();
        createClassFile.toFront();
       
}//openCreateRecord()

    //when setMaximum is called, the form will fit into the JDesktopPane,
    //it cannot then be moved outside of the JDesktopPane area.
    //the JTextField gets the focus, the blinking cursor.
void checkMaximized(){
    if(!isMaximum())
        try {
            setMaximum(true);
            firstNameTxtFld.requestFocusInWindow();
        } 
        catch (PropertyVetoException ex) {
            Logger.getLogger(SelectClassTeacher.class.getName()).log(Level.SEVERE, null, ex);
        }
}//checkMaximied()

    
    @Override
    public void mouseClicked(MouseEvent e) {
            checkMaximized();
    }
    @Override
    public void mousePressed(MouseEvent e) {   }

    @Override
    public void mouseReleased(MouseEvent e) {   }

    @Override
    public void mouseEntered(MouseEvent e) {   }

    @Override
    public void mouseExited(MouseEvent e) { }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel btnPane;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox classComBox;
    private javax.swing.JLabel classLbl;
    private javax.swing.JButton contBtn;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField firstNameTxtFld;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JPanel infoPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel labelPane;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTxtFld;
    // End of variables declaration                   
}//class SelectClassTeacher